config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :index, :new, :create, :show ] do
    resources :reviews, only: [:index, :new, :create ]
  end

  resources :reviews, only: [:show]

  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end


  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants list</h1>
<% @restaurants.each do |restaurant| %>
<p><%= link_to restaurant.name, restaurant_path(restaurant)  %></p>
<% end %>
<br>
<%= link_to "add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w(chinese italian japanese french belgian), as: :radio_buttons %>
  <%= f.submit "New restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<br>
<%= link_to "back", root_path  %>
<br>
<%= link_to "see all reviews", restaurant_reviews_path(@restaurant)  %>
<br>
<%= link_to "write a review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
<h3><%= review.restaurant.name %></h3>
<p><%= review.content %></p>
<p><%= review.rating %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "New review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h3><%= @review.restaurant.name %></h3>
<p><%= @review.content %></p>
<p><%= @review.rating %></p>

<%= link_to "back to restaurant list", restaurants_path  %>